stages:
  - build
  - test
  - deploy

variables:
  AWS_DEFAULT_REGION: "your_region"
  AWS_ACCESS_KEY_ID: "$AWS_ACCESS_KEY_ID"
  AWS_SECRET_ACCESS_KEY: "$AWS_SECRET_ACCESS_KEY"
  AWS_DEFAULT_OUTPUT: "json"

maven_build:
  stage: build
  script:
    - mvn clean install
  artifacts:
    paths:
      - target/demo-0.0.1-SNAPSHOT.war


test_app:
  stage: test
  script:
    - echo "Running tests..."
    # Add your test commands here
  after_script:
    - echo "Tests completed."

# This stage to put inmage into ECR
docker_build:
  stage: deploy
  script:
    - echo "$AWS_ECR_REGISTRY_PASSWORD" | docker login --username "$AWS_ECR_REGISTRY_USERNAME" --password-stdin "$AWS_ECR_REGISTRY_URL"
    - docker build -t $AWS_ECR_REGISTRY_URL/$AWS_ECR_REPOSITORY_NAME .
    - docker push $AWS_ECR_REGISTRY_URL/$AWS_ECR_REPOSITORY_NAME
  only:
    - main

#This stage to deploy Image pushed in ECR to EKS
deploy_to_eks:
  stage: deploy
  script:
    - echo "Deploying to Amazon EKS..."
    # kubectl rollout restart deployment $DEPLOYMENT-NAME -n NAMESPACE
  needs:
    - test_app
  when: on_success
  only:
    - main