stages:
  - build
  - test
  - deploy

variables:
  AWS_DEFAULT_REGION: "your_region"
  AWS_ACCESS_KEY_ID: "$AWS_ACCESS_KEY_ID"
  AWS_SECRET_ACCESS_KEY: "$AWS_SECRET_ACCESS_KEY"
  AWS_DEFAULT_OUTPUT: "json"

maven_build:
  stage: build
  script:
    - mvn clean install
  artifacts:
    paths:
      - target/demo-0.0.1-SNAPSHOT.war


test_app:
  stage: test
  script:
    - echo "Running tests..."
    # Add your test commands here
  after_script:
    - echo "Tests completed."

deploy_to_eks:
  stage: deploy
  script:
    - echo "Deploying to Amazon EKS..."
    # Add your deployment commands here
  needs:
    - test_app
  when: on_success
  only:
    - master